/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FdsAccordion {
        "accordionId": string;
        /**
          * The first name
         */
        "header": string;
        "showInfo": boolean;
    }
}
declare global {
    interface HTMLFdsAccordionElement extends Components.FdsAccordion, HTMLStencilElement {
    }
    var HTMLFdsAccordionElement: {
        prototype: HTMLFdsAccordionElement;
        new (): HTMLFdsAccordionElement;
    };
    interface HTMLElementTagNameMap {
        "fds-accordion": HTMLFdsAccordionElement;
    }
}
declare namespace LocalJSX {
    interface FdsAccordion {
        "accordionId"?: string;
        /**
          * The first name
         */
        "header"?: string;
        "showInfo"?: boolean;
    }
    interface IntrinsicElements {
        "fds-accordion": FdsAccordion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fds-accordion": LocalJSX.FdsAccordion & JSXBase.HTMLAttributes<HTMLFdsAccordionElement>;
        }
    }
}
